export enum PromotionType {
  WEB_DEVELOPMENT = 'WEB_DEVELOPMENT',
  APP_DEVELOPMENT = 'APP_DEVELOPMENT',
  DIGITAL_MARKETING = 'DIGITAL_MARKETING',
  SOCIAL_MEDIA_MARKETING = 'SOCIAL_MEDIA_MARKETING',
  BRAND_IDENTITY_DESIGN = 'BRAND_IDENTITY_DESIGN',
}
