export enum PromotionType {
  WEB_DEVELOPMENT = 'WEB_DEVELOPMENT',
  APP_DEVELOPMENT = 'APP_DEVELOPMENT',
  DIGITAL_MARKETING = 'DIGITAL_MARKETING',
  CONTENT_CREATION = 'CONTENT_CREATION',
  BRANDING = 'BRANDING',
  TRANING_AND_DEVELOPMENT = 'TRANING_AND_DEVELOPMENT',
}
