/* eslint-disable prettier/prettier */
export class EmailTemplateProvider {
  private static companyName = "Smartiv Hauz";
  private static logoUrl = "https://www.smartivhauz.com/images/logo.png";
  private static accentColor = "#F7941D";

  /**
   * Generates the admin notification email HTML.
   * Sent internally when a user submits a quote.
   */
  static generateAdminQuoteTemplate(params: {
    name: string;
    email: string;
    phone_number: string;
    company_name?: string;
    services: string[];
  }) {
    const { name, email, phone_number, company_name, services } = params;

    return `
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>New Quote Notification</title>
        <style>
          body { font-family: Arial, sans-serif; background-color: #f9f9f9; margin: 0; padding: 0; }
          .container { max-width: 600px; margin: 0 auto; background: #fff; border-radius: 8px; overflow: hidden; }
          .header { background-color: ${this.accentColor}; padding: 16px; text-align: center; }
          .header img { height: 40px; }
          .content { padding: 24px; color: #333; }
          h2 { color: ${this.accentColor}; margin-bottom: 16px; }
          table { width: 100%; border-collapse: collapse; }
          td { padding: 8px; vertical-align: top; }
          td:first-child { font-weight: bold; width: 35%; }
          .footer { background-color: #f2f2f2; text-align: center; padding: 12px; font-size: 13px; color: #666; }
          @media screen and (max-width: 600px) {
            .content { padding: 16px; }
          }
        </style>
      </head>
      <body>
        <div class="preheader" style="display:none;visibility:hidden;opacity:0;height:0;">
          A new quote request has been received on ${this.companyName}.
        </div>
        <div class="container">
          <div class="header">
            <img src="${this.logoUrl}" alt="${this.companyName} Logo" />
          </div>
          <div class="content">
            <h2>📩 New Quote Request Received</h2>
            <p>A new quote request has been submitted via your website:</p>

            <table>
              <tr><td>Name:</td><td>${name}</td></tr>
              <tr><td>Email:</td><td>${email}</td></tr>
              <tr><td>Phone Number:</td><td>${phone_number}</td></tr>
              ${company_name ? `<tr><td>Company:</td><td>${company_name}</td></tr>` : ""}
              <tr><td>Requested Services:</td><td>${services.join(", ")}</td></tr>
            </table>

            <p style="margin-top: 20px; font-size: 13px; color: #666;">
              Please follow up with this lead promptly. This message was automatically generated by ${this.companyName}.
            </p>
          </div>
          <div class="footer">
            &copy; ${new Date().getFullYear()} ${this.companyName}. All rights reserved.
          </div>
        </div>
      </body>
      </html>
    `;
  }

  /**
   * Generates the user-facing acknowledgment email HTML.
   * Sent to users after submitting a quote.
   */
  static generateUserQuoteReceiverTemplate(params: {
    name: string;
    company_name?: string;
  }) {
    const { name, company_name } = params;

    return `
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Quote Received</title>
        <style>
          body { font-family: Arial, sans-serif; background-color: #f9f9f9; margin: 0; padding: 0; }
          .container { max-width: 600px; margin: 0 auto; background: #fff; border-radius: 8px; overflow: hidden; }
          .header { background-color: ${this.accentColor}; padding: 16px; text-align: center; }
          .header img { height: 40px; }
          .content { padding: 24px; color: #333; text-align: left; }
          h2 { color: ${this.accentColor}; margin-bottom: 16px; text-align: center; }
          a.button { background-color: ${this.accentColor}; color: #fff; text-decoration: none; padding: 12px 20px; border-radius: 6px; display: inline-block; margin-top: 24px; font-weight: bold; }
          .footer { background-color: #f2f2f2; text-align: center; padding: 12px; font-size: 13px; color: #666; }
          @media screen and (max-width: 600px) {
            .content { padding: 16px; }
          }
        </style>
      </head>
      <body>
        <div class="preheader" style="display:none;visibility:hidden;opacity:0;height:0;">
          Thank you for your quote request — the ${this.companyName} team has received it.
        </div>
        <div class="container">
          <div class="header">
            <img src="${this.logoUrl}" alt="${this.companyName} Logo" />
          </div>
          <div class="content">
            <h2>Quote Request Received ✅</h2>
            <p>Hi <strong>${name}</strong>${company_name ? ` from <strong>${company_name}</strong>` : ""},</p>

            <p style="line-height: 1.6;">
              Thank you for reaching out! We’ve successfully received your quote request and our team will review your details shortly.
              You can expect a response within the next 24–48 hours.
            </p>

            <div style="text-align: center;">
              <a href="https://www.smartivhauz.com" class="button">Visit Our Website</a>
            </div>

            <p style="font-size: 12px; color: #888; margin-top: 30px; text-align: center;">
              This is an automated message. Please do not reply to this email.
            </p>
          </div>
          <div class="footer">
            &copy; ${new Date().getFullYear()} ${this.companyName}. All rights reserved.
          </div>
        </div>
      </body>
      </html>
    `;
  }

  static addTemplateHeader(body:string){
    return (
      `
       <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Quote Received</title>
        <style>
          body { font-family: Arial, sans-serif; background-color: #f9f9f9; margin: 0; padding: 0; }
          .container { max-width: 600px; margin: 0 auto; background: #fff; border-radius: 8px; overflow: hidden; }
          .header { background-color: ${this.accentColor}; padding: 16px; text-align: center; }
          .header img { height: 40px; }
          .content { padding: 24px; color: #333; text-align: left; }
          h2 { color: ${this.accentColor}; margin-bottom: 16px; text-align: center; }
          a.button { background-color: ${this.accentColor}; color: #fff; text-decoration: none; padding: 12px 20px; border-radius: 6px; display: inline-block; margin-top: 24px; font-weight: bold; }
          .footer { background-color: #f2f2f2; text-align: center; padding: 12px; font-size: 13px; color: #666; }
          @media screen and (max-width: 600px) {
            .content { padding: 16px; }
          }
        </style>
      </head>
      <body>
       
        <div class="container">
          <div class="header">
            <img src="${this.logoUrl}" alt="${this.companyName} Logo" />
          </div>
          <div class="content">
             ${body}
            <p style="font-size: 12px; color: #888; margin-top: 30px; text-align: center;">
              This is an automated message. Please do not reply to this email.
            </p>
          </div>
          <div class="footer">
            &copy; ${new Date().getFullYear()} ${this.companyName}. All rights reserved.
          </div>
        </div>
      </body>
      </html>
      `
    )
  }

}
