# syntax=docker/dockerfile:1.4

# ------------------------------
# Stage 1: Builder (with Python & build tools)
# ------------------------------
FROM node:20-slim AS builder

WORKDIR /smartiv_hauz_server

# Install build tools for native modules
RUN apt-get update && apt-get install -y python3 make g++ && rm -rf /var/lib/apt/lists/*

# Copy package files and install all dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# If .env exists locally or was generated by CI, use it during build (not copied to final image)
RUN --mount=type=secret,id=env,target=/tmp/.env \
    sh -c "if [ -f /tmp/.env ]; then cp /tmp/.env .env; fi && npm run build"

# ------------------------------
# Stage 2: Production
# ------------------------------
FROM node:20-slim AS production

WORKDIR /smartiv_hauz_server

# Copy package files and install only production dependencies
COPY package*.json ./
RUN npm install --omit=dev

# Copy built app only (no .env copied)
COPY --from=builder /smartiv_hauz_server/dist ./dist

# Expose application port
EXPOSE 3000

# Start the NestJS app
CMD ["npm", "run","start:prod"]
